import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useHouseholdStore } from "@/stores/householdStore";
import type { Household, HouseholdMember, HouseholdInvite } from "@/types/app.types";

export function useHousehold(householdId: string | undefined) {
  return useQuery({
    queryKey: ["household", householdId],
    queryFn: async () => {
      if (!householdId) return null;
      const { data, error } = await supabase
        .from("households")
        .select("*")
        .eq("id", householdId)
        .single();
      if (error) throw error;
      return data as Household;
    },
    enabled: !!householdId,
  });
}

export function useHouseholdMembers(householdId: string | undefined) {
  return useQuery({
    queryKey: ["household_members", householdId],
    queryFn: async () => {
      if (!householdId) return [];
      const { data, error } = await supabase
        .from("household_members")
        .select("*")
        .eq("household_id", householdId)
        .order("joined_at");
      if (error) throw error;
      return (data ?? []) as HouseholdMember[];
    },
    enabled: !!householdId,
  });
}

export function useCreateHousehold() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      name,
      zipCode,
      userId,
      displayName,
    }: {
      name: string;
      zipCode: string;
      userId: string;
      displayName: string;
    }) => {
      const { data, error } = await supabase.rpc("create_household_with_member", {
        p_name: name,
        p_zip_code: zipCode,
        p_user_id: userId,
        p_display_name: displayName,
      });
      if (error) throw error;
      return data as Household;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["household"] }),
  });
}

// ── Household Invites ─────────────────────────────────────────────────────────

export function useHouseholdInvites(householdId: string | undefined) {
  return useQuery({
    queryKey: ["household_invites", householdId],
    queryFn: async () => {
      if (!householdId) return [];
      const { data, error } = await supabase
        .from("household_invites")
        .select("*")
        .eq("household_id", householdId)
        .is("accepted_at", null)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as HouseholdInvite[];
    },
    enabled: !!householdId,
  });
}

export function useSendInvite() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      householdId,
      email,
      name,
      role,
      invitedBy,
    }: {
      householdId: string;
      email: string;
      name: string;
      role: "admin" | "editor" | "viewer";
      invitedBy: string;
    }) => {
      // Remove any existing invite for this email+household (including accepted ones)
      // so the UNIQUE(household_id, email) constraint doesn't block re-invites
      await supabase
        .from("household_invites")
        .delete()
        .eq("household_id", householdId)
        .eq("email", email);

      // Insert fresh invite record (token auto-generated by DB default)
      const { data: invite, error } = await supabase
        .from("household_invites")
        .insert({ household_id: householdId, email, name, role, invited_by: invitedBy })
        .select()
        .single();
      if (error) throw error;

      // Call Edge Function to send email
      const { data: fnData, error: fnError } = await supabase.functions.invoke("invite-member", {
        body: { email, name, token: invite.token, householdId },
      });

      let fnErrorMessage: string | null = null;
      const existingUser: boolean = !fnError && !!(fnData as any)?.existingUser;
      const actionLink: string | null = !fnError ? ((fnData as any)?.actionLink ?? null) : null;

      if (fnError) {
        try {
          const body = await (fnError as any).context?.json?.();
          fnErrorMessage = body?.error ?? fnError.message ?? "Unknown error";
        } catch {
          fnErrorMessage = fnError.message ?? "Unknown error";
        }
      }

      return { invite: invite as HouseholdInvite, emailSent: !fnError, fnErrorMessage, existingUser, actionLink };
    },
    onSuccess: (_, { householdId }) =>
      qc.invalidateQueries({ queryKey: ["household_invites", householdId] }),
  });
}

export function useResendInvite() {
  return useMutation({
    mutationFn: async ({
      email,
      name,
      token,
      householdId,
    }: {
      email: string;
      name: string;
      token: string;
      householdId: string;
    }) => {
      const { data: fnData, error } = await supabase.functions.invoke("invite-member", {
        body: { email, name, token, householdId },
      });
      if (error) {
        let msg = error.message ?? "Email could not be sent.";
        try {
          const body = await (error as any).context?.json?.();
          if (body?.error) msg = body.error;
        } catch {}
        throw new Error(msg);
      }
      const existingUser: boolean = !!(fnData as any)?.existingUser;
      const actionLink: string | null = (fnData as any)?.actionLink ?? null;
      return { existingUser, actionLink };
    },
  });
}

export function useDeleteInvite() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, householdId }: { id: string; householdId: string }) => {
      const { error } = await supabase
        .from("household_invites")
        .delete()
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: (_, { householdId }) =>
      qc.invalidateQueries({ queryKey: ["household_invites", householdId] }),
  });
}

export function useDeleteMember() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, householdId }: { id: string; householdId: string }) => {
      const { error } = await supabase
        .from("household_members")
        .delete()
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: (_, { householdId }) =>
      qc.invalidateQueries({ queryKey: ["household_members", householdId] }),
  });
}

export function useUpdateMemberRole() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      id,
      householdId,
      role,
    }: {
      id: string;
      householdId: string;
      role: "admin" | "editor" | "viewer" | "member";
    }) => {
      const { error } = await supabase
        .from("household_members")
        .update({ role })
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: (_, { householdId }) =>
      qc.invalidateQueries({ queryKey: ["household_members", householdId] }),
  });
}

export function useAcceptInvite() {
  return useMutation({
    mutationFn: async ({
      token,
      userId,
      displayName,
    }: {
      token: string;
      userId: string;
      displayName: string;
    }) => {
      const { data, error } = await supabase
        .from("household_members")
        .update({ user_id: userId, display_name: displayName })
        .eq("invite_token", token)
        .select()
        .single();
      if (error) throw error;
      return data as HouseholdMember;
    },
  });
}
